# Generated by Django 4.2.7 on 2024-01-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'verbose_name_plural': 'Data Detail Transaksi'},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name_plural': 'Data Transaksi'},
        ),
    ]
